import torch
import os
import torch.nn as nn
from person_classifier_model import PersonClassifierCNN
# from your_model_file import PersonClassifierCNN

def export_fused_int8_header(pth_path, h_file_path):
    print(f"[{pth_path}] 파일에서 가중치를 읽어옵니다...")
    
    # 1. 모델 로드 (평가 모드로 변경 필수)
    model = PersonClassifierCNN()
    model.load_state_dict(torch.load(pth_path, map_location='cpu'))
    model.eval()

    # 2. BN Folding을 적용하여 Fused Dictionary 생성
    fused_state_dict = {}
    
    for name, module in model.named_modules():
        if isinstance(module, nn.Conv2d):
            # Conv2d 이름과 짝이 맞는 BatchNorm2d 모듈 찾기 (예: conv1_1 -> bn1_1)
            bn_name = name.replace('conv', 'bn')
            bn_module = dict(model.named_modules()).get(bn_name)
            
            if bn_module is not None and isinstance(bn_module, nn.BatchNorm2d):
                print(f"[BN Folding 적용] {name} + {bn_name}")
                
                # Conv 가중치 및 편향 (편향이 없으면 0으로 초기화)
                w = module.weight.data
                b = module.bias.data if module.bias is not None else torch.zeros(w.size(0))
                
                # BatchNorm 파라미터
                gamma = bn_module.weight.data
                beta = bn_module.bias.data
                mean = bn_module.running_mean
                var = bn_module.running_var
                eps = bn_module.eps
                
                # ==========================================
                # 수학적 병합 공식 적용
                # Scale = gamma / sqrt(var + eps)
                # W_new = W * Scale
                # B_new = (B - mean) * Scale + beta
                # ==========================================
                scale = gamma / torch.sqrt(var + eps)
                
                w_fused = w * scale.view(-1, 1, 1, 1)
                b_fused = (b - mean) * scale + beta
                
                fused_state_dict[f"{name}_fused_weight"] = w_fused
                fused_state_dict[f"{name}_fused_bias"] = b_fused
            else:
                # BN이 없는 Conv 레이어 처리
                fused_state_dict[f"{name}_weight"] = module.weight.data
                if module.bias is not None:
                    fused_state_dict[f"{name}_bias"] = module.bias.data
                    
        elif isinstance(module, nn.Linear):
            # FC 레이어 처리
            fused_state_dict[f"{name}_weight"] = module.weight.data
            if module.bias is not None:
                fused_state_dict[f"{name}_bias"] = module.bias.data

    # 3. 양자화 및 C 헤더 파일 작성
    with open(h_file_path, 'w') as f:
        f.write("/* \n")
        f.write(" * Person Classifier CNN - BN Fused & Quantized Weights\n")
        f.write(" * [Weights: INT8, Bias: INT32]\n")
        f.write(" * Auto-generated by PyTorch Script\n")
        f.write(" */\n\n")
        f.write("#ifndef PERSON_CLASSIFIER_INT8_H\n")
        f.write("#define PERSON_CLASSIFIER_INT8_H\n\n")
        f.write("#include <stdint.h>\n\n")

        for name, tensor in fused_state_dict.items():
            shape = list(tensor.shape)
            flat_data = tensor.flatten().tolist()
            
            # 텐서의 최대값을 기준으로 스케일 계산
            max_val = torch.max(torch.abs(tensor)).item()
            
            # ==========================================
            # 🌟 가중치(INT8)와 바이어스(INT32) 분리 양자화
            # ==========================================
            is_bias = 'bias' in name
            
            if is_bias:
                # [바이어스] INT32 (32비트)로 처리
                quant_scale = 1.0 if max_val == 0 else max_val / 2147483647.0
                q_tensor = torch.round(tensor / quant_scale)
                q_tensor = torch.clamp(q_tensor, -2147483648, 2147483647).to(torch.int32)
                c_data_type = "int32_t"
                # C코드 정렬을 위해 32비트는 11자리, 8비트는 4자리 확보
                print_format = "{:11d}, " 
            else:
                # [가중치] INT8 (8비트)로 처리
                quant_scale = 1.0 if max_val == 0 else max_val / 127.0
                q_tensor = torch.round(tensor / quant_scale)
                q_tensor = torch.clamp(q_tensor, -128, 127).to(torch.int8)
                c_data_type = "int8_t"
                print_format = "{:4d}, "

            flat_q_data = q_tensor.flatten().tolist()
            c_name = name.replace('.', '_')
            
            # 주석 작성 (Shape 정보)
            f.write(f"// Layer: {name} | Original Max: {max_val:.6f}\n")
            f.write(f"// PyTorch Shape: {shape} ")
            if len(shape) == 4:
                f.write("-> Fused Conv2d Weight [out_ch, in_ch, k_h, k_w]\n")
            elif len(shape) == 2:
                f.write("-> Linear Weight [out_features, in_features]\n")
            elif len(shape) == 1:
                f.write("-> Bias 1D Vector [features]\n")
            else:
                f.write("\n")
                
            f.write(f"const float {c_name}_scale = {quant_scale}f;\n")
            f.write(f"const int {c_name}_len = {len(flat_q_data)};\n")
            
            # 분리된 데이터 타입(int8_t 또는 int32_t) 적용
            f.write(f"const {c_data_type} {c_name}[{len(flat_q_data)}] = {{\n")
            
            # 출력 채널별 주석 분리
            if len(shape) >= 2:
                out_dim = shape[0]
                chunk_size = len(flat_q_data) // out_dim
                
                for i in range(out_dim):
                    f.write(f"    // --- Output Channel / Feature [{i}] ---\n    ")
                    chunk = flat_q_data[i * chunk_size : (i + 1) * chunk_size]
                    for j, val in enumerate(chunk):
                        f.write(print_format.format(val))
                        if (j + 1) % 12 == 0 and j != len(chunk) - 1:
                            f.write("\n    ")
                    f.write("\n")
            else:
                f.write("    ")
                for i, val in enumerate(flat_q_data):
                    f.write(print_format.format(val))
                    if (i + 1) % 12 == 0 and i != len(flat_q_data) - 1:
                        f.write("\n    ")
                f.write("\n")
                
            f.write("};\n\n")

        f.write("#endif // PERSON_CLASSIFIER_INT8_H\n")
    
    print(f"\n🎉 BN Folding 및 양자화 완료! 파일이 성공적으로 생성되었습니다: {os.path.abspath(h_file_path)}")

if __name__ == "__main__":
    export_fused_int8_header('./save_pt/person_classifier.pth', './save_pt/weights_int8_fused.h')